server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sithumini-silva/GMS_config_repo.git # TODO: Replace with your actual Git config repository URI
          default-label: main

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/